version: '0.2'
services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     # 映射nginx.conf文件到容器的/etc/nginx/conf.d目录并覆盖default.conf文件
     - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
     # 映射build文件夹到容器的/usr/share/nginx/html文件夹
     - ./build/prod:/usr/share/nginx/html
