export const ACTION_TYPES = {
  FETCH_QUICK_LIST_TASKS_SUCCEEDED: 'FETCH_QUICK_LIST_TASKS_SUCCEEDED',
  FETCH_GRASS_CATCHER_TASKS_SUCCEEDED: 'FETCH_GRASS_CATCHER_TASKS_SUCCEEDED',
  FETCH_COMPLETED_TASKS_SUCCEEDED: 'FETCH_COMPLETED_TASKS_SUCCEEDED',
}
